### PR TITLE
Support multiple children per outlet

### PR DESCRIPTION
**Pull request by hmans**
This PR adds support for multiple `In` children for a single `Out`:

- `tunnel.In` can now be used multiple times to inject multiple "rats" into the same outlet.
- The main way this works is that the internal store now keeps a _list of rats_ instead of just a single rat.
- The trickier part was to get the ordering behavior right in case of individual rats un- and then remounting. To get this right, the internal state uses an internal version number that is bumped every time a rat is _added_. When the version number is bumped, _all existing rats will be re-rendered_. This might sound a little scary at first, but it simply matches the behavior of a normal React component rendering a list, where every update to the list will also cause the children to be re-rendered.

Please let me know what you think of the solution. This branch is based off of that one PR that adds tests, so please merge that one first. (#8)

#### Todo:

- [x] Set up a demo CSB
  - https://codesandbox.io/s/tunnel-rat-demo-ceupre?file=/src/App.tsx
- [x] ~Update README~
  - There wasn't much to update. ;-) I would like to give the README a general overhaul, but would prefer to do it outside of this PR.

#### Additional notes:

- This has the potential of being a **breaking change**, in case apps out there are relying on the previous behavior. I recommend releasing this as part of the next minor or major version.
- I believe this also fixes the HMR issue reported in #4.
- I had to change `index.ts` into `index.tsx` to be able to wrap the outlet's children in a Fragment. If there is another way of safely returning children that satisfies React and its types and doesn't require a fragment (and thus .tsx), I would prefer it (but generally speaking, the .tsx is also not the end of the world.)
- There's probably a bunch of opportunities to upgrade dependencies (Zustand!) and clean things up a little, but other than some comments and updated types, I've refrained from them, in order for this PR to not grow too large. But I'd be happy to take care of some of that stuff in separate PRs.

### CODE REVIEW

**Comment by hmans** [comment]
I've tested this in the app where I'm using tunnel-rat, and it works great so far.

**Comment by hmans** [comment]
I think this change is solid, so I'm going to un-draft this. Let me know what you think, and if you would prefer any changes made.

**Comment by hmans** [comment]
Demo CSB: https://codesandbox.io/s/tunnel-rat-demo-ceupre?file=/src/App.tsx

**Comment by hmans** [comment]
I would like to give the README a general overhaul, but would prefer to do it outside of this PR.

You've added me to the repo's admins (thanks!), but I don't want to just self-merge this. I'd appreciate if you (or someone else) took a look at the CSB I've set up to try and break things (or identify any other issues I'm not yet seeing.) Thanks!

**Comment by CodyJasonBennett** [comment]
Can confirm this fixes HMR.

**Comment by hmans** [comment]
I've spotted an edge case that needs fixing, so it's back to draft status.

**Comment by hmans** [comment]
False alert, I could not reproduce it with the implementation here. All is good.

**Comment by hmans** [comment]
How do you guys want to proceed with this? Paul has made me an admin of this repository. Should I self-merge?

**Review by CodyJasonBennett — APPROVED** [review]
Looks good. Feel free to merge.

**Pull request merged**
