### PR TITLE
[Breaking] Use a central store to avoid hmr rendering issues

### LINKED ISSUE #4: Doesn't re-render on HMR
I'm using vite and in dev mode when HMR happens on a module that calls a tunnel, the tunnel itself isn't re-rendered.

I've written a helper as a work-around:

```ts
import t from 'tunnel-rat'

export const tunnel = (key: string) => {
  if (import.meta.hot) {
    const fullKey = `tunnel-${key}`
    if (import.meta.hot.data[fullKey]) {
      return import.meta.hot.data[fullKey]
    }
    import.meta.hot.data[fullKey] = t()
    return import.meta.hot.data[fullKey]
  }
  return t()
}
```

The helper requires a key so that it can persist the tunnel instance in `import.meta.hot.data`. I'm not incredibly experienced in HMR, so I'm not sure if there's a better solution here.

I believe the issue may have been masked before because we were never clearing the tunnel contents.

### PR DESCRIPTION
**Pull request by just-be-dev**
Fixes #4 

I was hoping that #9 might've fixed the HMR issue I was seeing in #4, but it doesn't seem to have. 

## Background

The HMR issue I'm seeing is that when a component that has a tunnel declaration in the same file is hot reloaded the tunnel's outlets either fail to render or fail to update (thus rendering old content). I believe this is because the tunnel is actually recreated during HMR but perhaps the outlets are orphaned? I'm not 100%. 

here's a rough example of the kind of code that'd trigger the bug I'm talking about: 

```tsx
import tunnel from 'tunnel-rat'

const Tunnel = tunnel()

export function Test() {

  return (
    <Tunnel.In>
      <span>test</span>
    </Tunnel.In>
  )
}

Test.Target = Tunnel.Out
```

Editing this file means that where `Test.Target` is used wouldn't render the correct value after HMR of this file.

I posted an example of how I fixed this in #4. It was essentially by using vite's meta caching layer to only ever create the tunnel once. Later I realized  an alternative way of doing this was just by using zustand itself. 

This PR moves the store out of the `tunnel` function and centralizes it. Each tunnel is stored in a `tunnels` object from the main store and a string key value is required for each `tunnel` invocation. No matter how many times a tunnel reinitialized, it'll still 

## Breaking change

This change requires people's code to go from

`const t = tunnel()` to `const t = tunnel('my-tunnel')`

## Tradeoffs

Once a tunnel is initialized at least its default data will always stick around. After the last `In` component for that named tunnel has unmounted it'll just be the `version` number and an empty array for current. I suspect this wouldn't be an issue unless someone had a _large_ amount of tunnels.

### CODE REVIEW

**Comment by hmans** [comment]
Thanks for the PR! I will take a look at this some time this weekend.

**Comment by hmans** [comment]
I've whipped up a simple Vite 3 app with the current code from `main` to do some testing:

https://github.com/hmans/tunnel-rat-debug

I initially created the tunnel in my `App.tsx`, which led to any module that imported the tunnel from that file to reset the tunnel (even though I can't tell for sure if this was a matter of the tunnel itself resetting to a blank state, or Vite remounting all components, since it started from the root.)

**I solved all of these problems by moving the tunnel into its own module**, and importing from that, which happens to be the same pattern you'd use for any other store, except of course it's not immediately obvious to the user that they're dealing with a stateful store. Specifically asking the user to create and export their tunnels from a stand-alone module in order to prevent HMR issues would not be my preferred solution for this.

Having said that, explicitly naming tunnels also seems like a pretty heavy-weight change in terms of DX, but also implementational complexity. This is not my library, so the decision is not up to me (pinging @drcmda), I just hang out here and tidy things up a little :) but maybe there's another, maybe less invasive approach waiting to be found?

**Comment by just-be-dev** [comment]
Thanks for the repo and investigation @hmans. I'm certainly open to simpler solutions, but this is the simplest I could come up with. From a user's perspective the usage difference is negligible. There is some slight added implementational complexity, but I still feel it's worth the tradeoff. 

Again, I'm open to simpler solutions. I've moved our codebase over to use this as a patch so we're not blocked on it, but it's worth consideration because I'm sure other users will stumble into this.

**Comment by lunacrafts** [comment]
I like this approach. It would make cases with dynamically created tunnels easier to handle. I don't like additional complexity but I think It's fair trade off.

**Comment by CodyJasonBennett** [comment]
What about a hooks-based approach?

**Comment by just-be-dev** [comment]
@CodyJasonBennett would you mind articulating further on that? Just by the limited context I'm not sure what you mean.

My ultimate goal here was to eliminate this odd edge case with as little changes to the existing API as possible. If there's a better way to accomplish this with no required API changes I'm definitely 100% open to it. If there's a way to implemented it with less internal complexity I'm also open to that. Granted, I do confess that while I'll acknowledge this approach isn't as internally simple as the previous, neither do I see it that much more complex. The shape of tunnel state has state consistent, it's now just stored in a singular unified store instead of many stores generated by closures. I'm certainly not tied to the implementation though. Please, help me make it simpler if you can!

**Comment by CodyJasonBennett** [comment]
Sorry, to clarify my original (now-deleted) comment was:

> Why not a hooks-based approach?

This issue seems to be a pitfall of the current design having global stores that aren't localized to a component or tree. I was curious as to why tunnel-rat wasn't designed around hooks that have a lifecycle and can use render effects to play nice with HMR.

I removed my comment since this doesn't play nice with cross-renderer/container stuff and I don't think I quite understand the premise.

**Comment by just-be-dev** [comment]
Ahh, you didn't have to delete it! The long winded part wasn't aimed at you, just a general statement, haha. Sorry if it came off otherwise.

This library being oriented around a global store is its defining property. There are other portal implementations that use hooks.

A benefit of this approach is you can do things like... render across entirely different react trees! There's less setup too (no context provider needed). Overall, it's just a different approach with different constraints.

**Comment by lunacrafts** [comment]
> There are other portal implementations that use hooks.

@zephraph Do you have any specific package in mind? Could you point them out?
I know few portal solution, but none of them are so clear and JSX-ish as this one. I'd be happy to see hooks approach on top of solution from this PR.

**Comment by just-be-dev** [comment]
@lunacrafts https://github.com/wellyshen/react-cool-portal is an example. It's more a traditional portal implementation (so you can't do everything with it that you could with this), but it does use hooks. Alternatives is a bit off topic though.

@hmas, barring @drcmda approving or denying, is there something I could do for this PR to make it a bit more palatable? Is the biggest sticking point the internal implementation or the API change? I'm willing to work through alternatives. I honestly just want to be able to use this library instead of forking it just so it'll work with hmr.

**Comment by hmans** [comment]
> @hmas, barring @drcmda approving or denying, is there something I could do for this PR to make it a bit more palatable? Is the biggest sticking point the internal implementation or the API change? I'm willing to work through alternatives. I honestly just want to be able to use this library instead of forking it just so it'll work with hmr.

I'm honestly the wrong person to ask. This isn't my project, nor am I the maintainer (I just happened to be promoted to an admin by @drcmda  so I wouldn't need to bug him for every little thing. :b)

If this _were_ my project (and, once again, it's not), I would most likely reject the PR, but I'm a bit of a terrible open source maintainer that way, because I am extremely defensive of my APIs, and usually try to avoid complicating them if there is a simpler solution or workaround. (Which, I believe, in this case is defining your tunnels in a separate module, just like you would do with any normal store. In my testing, this solved all HMR issues, but also that testing might not have been exhaustive.)

I would have the following issues with the solution presented here:

- It fixes a problem with added API that could also be worked around using a simpler solution (providing I am not wrong about the above.)
- It is unclear to me if (and how) tunnel names are typed. Does it introduce the potential for new errors (eg. users having typos in their tunnel name references)?

Now, once again, it is not my project and thus not my decision, I'm just trying to be open about my own thought process for transparency and possibly feedback (and also to possibly be proven wrong about all of it. :b)

**Comment by dennemark** [comment]
Thanks a lot! So helpful! Adapted it for my own solution :)
Interface did not change much, but DX is awesome now :)

**Comment by lunacrafts** [comment]
> Thanks a lot! So helpful! Adapted it for my own solution :)
> Interface did not change much, but DX is awesome now :)

Could you share any piece of code?

**Comment by dennemark** [comment]
It is the one provided by zephraph in this PR. My version is just a bit different, since I am using also a Record instead of Array for the children. So better stick to zephraphs version, if you need to.
Concerning the Record / Array issue, you can have a look here: https://github.com/pmndrs/tunnel-rat/issues/16

**Comment by just-be-dev** [comment]
I appreciate the considerations. Given that this isn't going to get merged and is a bit out of date I'm just going to close it. I hope the code here help some folks!

**Pull request closed without merging**
